# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pytanie')),
                ('answer', models.TextField(verbose_name='Odpowied\u017a')),
                ('date_add', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Issue')),
            ],
        ),
    ]
