# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='issue',
        ),
        migrations.AddField(
            model_name='tag',
            name='issue',
            field=models.ManyToManyField(to='app.Issue'),
        ),
    ]
